language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm

dist: trusty

matrix:
  fast_finish: true
  allow_failures:

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token: 28ebd9b89b0ba2f8e3f2d98bae1fbfc40c6d4ac6bb4294788d96261a798ed9a7

before_script:
  - sh .travis.install.sh
  - if [ `./.travis.check-php-version-old-phpunit.php` -eq "1" ]; then echo "old"; composer require --no-update "phpunit/phpunit":"^4"; else echo "new"; fi
  - composer install --verbose

script: if [ `./.travis.check-php-version-coverage.php` -eq "1" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi

after_script:
  - if [ `./.travis.check-php-version-coverage.php` -eq "1" ]; then vendor/bin/test-reporter; fi
